# syntax=docker/dockerfile:1

# this builds the mmsgate2 and lego go execs.  we'll run native and cross compile
FROM	--platform=$BUILDPLATFORM golang:latest AS gobuild

LABEL	org.opencontainers.image.authors="https://github.com/RVgo4it"

# need for cross compiling targets
ARG	BUILDPLATFORM
ARG	TARGETPLATFORM
ARG	TARGETOS
ARG	TARGETARCH

# we'll put output under /root
WORKDIR	/root

RUN	apt-get -y update; apt-get -y install \
	# Important: required for go-sqlite3
	gcc \
	# Required for Alpine
	musl-dev

# compile mmsgate2
RUN	mkdir ~/mmsgate2
COPY	--chown=root --chmod=755 mmsgate2/scripts/*.go mmsgate2/scripts/go.* /root/mmsgate2/
# if doing cross compile...  then add the needed GCC compiler
RUN	if [ ${TARGETPLATFORM} != ${BUILDPLATFORM} ] ; then \
	  if [ ${TARGETARCH} = arm ] ; then \
	    apt-get -y install gcc-arm-linux-gnueabihf && \
	    export CC=arm-linux-gnueabihf-gcc; \
	  fi && \
	  if [ ${TARGETARCH} = arm64 ] ; then \
	    apt-get -y install gcc-aarch64-linux-gnu && \
	    export CC=aarch64-linux-gnu-gcc; \
	  fi && \
	  if [ ${TARGETARCH} = amd64 ] ; then \
	    apt-get -y install gcc-x86-64-linux-gnu && \
	    export CC=x86_64-linux-gnu-gcc; \
	  fi ; \
	fi && \
	cd ~/mmsgate2 && \
	CGO_ENABLED=1 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -v -o ./mmsgate2

# compile lego
RUN	mkdir ~/lego
RUN	cd ~/lego && \
	GOOS=${TARGETOS} GOARCH=${TARGETARCH} go install -v github.com/go-acme/lego/v4/cmd/lego@latest
# copy exec to /root/lego...  check both /go/bin and /go/bin/os_arch
RUN	cp /go/bin/${TARGETOS}_${TARGETARCH}/lego ~/lego/ || cp /go/bin/lego ~/lego/

# This builds a MMSgate2 image from the OpenSIPS installed image
FROM	rvgo4it/opensips

LABEL	org.opencontainers.image.authors="https://github.com/RVgo4it"

USER	root
WORKDIR	/root

# install needed apps
RUN	apt -y update && \
	apt -y upgrade && \
	apt install -y curl \
	netcat-openbsd \
	net-tools \
	tor \
	nano \
	cron \
	jq \
	dumb-init \
	nginx \
	lynx \
	traceroute \
	rsyslog \
	iputils-tracepath \
	dnsutils

# Configure user mmsgate, with a little sudo
RUN	useradd -ms /bin/bash mmsgate && \
	echo 'mmsgate:notnot' | chpasswd && \
        echo 'mmsgate ALL=(ALL) NOPASSWD:SETENV:/etc/opensips/globalcfg.sh, /scripts/stopopensips.sh, /scripts/fwtestviator.sh, /scripts/fwtestviaproxy.sh, /scripts/certs.sh, /scripts/restart.sh, /scripts/displaylog.sh' >> /etc/sudoers

# Configure user opensips, no sudo
RUN	useradd -ms /bin/bash opensips && \
	echo 'opensips:notnot' | chpasswd

# Configure user mmsgateadm, with sudo
RUN	useradd -ms /bin/bash mmsgateadm && \
	echo 'mmsgateadm:notnot' | chpasswd && \
	echo 'mmsgateadm ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# bring over the scripts and other files
COPY	--chown=root mmsgate2/scripts/ /scripts/
COPY	--chown=root mmsgate2/globalcfg.txt mmsgate2/globalcfg.sh mmsgate2/opensips.cfg /etc/opensips/

# cron new config location
# have cron run preprocchk.sh every 10 minutes, dynudnschk.sh 5 minutes after that
# also, clean up media files (not xml, vcard or qrcode files) over 90 days old once a day, 2 am
# and clean up messages from over 30 days ago, sundays at 2:30 am
# finally compact the databases sundays at 2:45 am and 2:55 am
RUN	mv /var/spool/cron/crontabs /etc/opensips/ && \
	ln -s /etc/opensips/crontabs /var/spool/cron && \
	echo 'SHELL=/bin/bash' | crontab - && \
	{ crontab -l; echo '*/10 * * * * . /etc/profile; /scripts/preprocchk.sh'; } | crontab - && \
	{ crontab -l; echo '5,15,25,35,45,55 * * * * . /etc/profile; /scripts/dynudnschk.sh'; } | crontab - && \
	{ crontab -l; echo '0 2 * * * . /etc/opensips/globalcfg.sh; find $LOCALMEDIA -mtime +90 ! -name '"'"'contacts.vcard'"'"' ! -name '"'"'*.xml'"'"' ! -name '"'"'*-cfg.png'"'"' -delete'; } | crontab - && \
	{ crontab -l; echo '30 2 * * 0 . /etc/opensips/globalcfg.sh; sqlite3 $DBPATHM '"'"'DELETE FROM send_msgs WHERE rcvd_ts < CAST(strftime("%s",date("now","-30 days")) AS INTEGER);'"'"; } | crontab - && \
	{ crontab -l; echo '45 2 * * 0 . /etc/opensips/globalcfg.sh; sqlite3 $DBPATHM "VACUUM;"'; } | crontab - && \
	{ crontab -l; echo '55 2 * * 0 . /etc/opensips/globalcfg.sh; sqlite3 $DBPATH "VACUUM;"'; } | crontab -

# setup log files for opensips and mmsgate
RUN	echo 'local7.*        /var/log/opensips.log' > /etc/rsyslog.d/40-opensips.conf && \
	echo 'local7.*        stop' >> /etc/rsyslog.d/40-opensips.conf && \
	echo 'local6.*        /var/log/mmsgate.log' > /etc/rsyslog.d/41-mmsgate.conf && \
	echo 'local6.*        stop' >> /etc/rsyslog.d/41-mmsgate.conf

# setup log rotates.  includes opensips.log, mmsgate.log and nginx files and HUB/USR1 signal to reopen
RUN	sed --in-place 's_rsyslog-rotate_rsyslog-rotate\n\t\t/bin/kill -HUP $(cat /var/run/rsyslogd.pid)_' /etc/logrotate.d/rsyslog && \
	sed --in-place 's_invoke-rc.d nginx rotate_invoke-rc.d nginx rotate >/dev/null 2>&1\n\t\t/bin/kill -USR1 $(cat /var/run/nginx.pid)_' /etc/logrotate.d/nginx

# need some data folders
RUN	mkdir -m=777 /data /data/mmsmedia /data/mmsgate /data/opensips

# setup Nginx, new config location, no default site and bump up hash bucket
ARG	ADMPW="Apple99"
RUN	sed 's/\/etc\/nginx/\/etc\/opensips\/nginx/' -i /etc/nginx/nginx.conf && \
	sed 's/# server_names_hash_bucket_size/server_names_hash_bucket_size/' -i /etc/nginx/nginx.conf && \
	mv /etc/nginx /etc/opensips/ && \
	rm /etc/opensips/nginx/sites-enabled/default && \
	ln -s /etc/opensips/nginx /etc && \
	echo -n 'admin:' >> /etc/opensips/nginx/.htpasswd && \
	openssl passwd -apr1 ${ADMPW} >> /etc/opensips/nginx/.htpasswd && \
	chown mmsgate:mmsgate /etc/opensips/nginx/.htpasswd
COPY	--chown=root --chmod=755 mmsgate2/admin /etc/opensips/nginx/sites-available/
RUN	ln -fs /etc/opensips/nginx/sites-available/admin /etc/opensips/nginx/sites-enabled/admin

# setup group for shared db access
RUN	addgroup db && \
	adduser mmsgateadm db && \
	adduser mmsgate db && \
	adduser opensips db && \
	chown root:db /data/mmsgate && \
	chmod g+s /data/mmsgate

# get go exec
COPY	--from=gobuild /root/mmsgate2/mmsgate2 /scripts/
COPY	--from=gobuild /root/lego/lego /bin/lego

USER	mmsgateadm
WORKDIR	/home/mmsgateadm

# Startup config
ENTRYPOINT	["/usr/bin/dumb-init", "--"]
CMD	["/scripts/init.sh"]
EXPOSE	5061/tcp 38443/tcp 38000/tcp

